name: Pantheon Multidev Environments

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pantheon-multidev:
    runs-on: ubuntu-latest

    env:
      PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      MULTIDEV_ENV: pr-${{ github.event.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.2/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/

      - name: Install Terminus Build Tools
        run: |
          terminus self:plugin:install terminus-build-tools-plugin

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token="$PANTHEON_MACHINE_TOKEN"

      - name: Create or Update Multidev Environment
        if: github.event.action != 'closed'
        run: |  
          terminus build:env:create $PANTHEON_SITE_ID.dev $MULTIDEV_ENV --yes

      - name: Prepare code for deployment
        if: github.event.action != 'closed'
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          commit_message=$(git log -1 --pretty=%B)
          rm -rf .git
          rm -rf .github
          rm -rf scripts
          rm -rf web/core/*.txt
          git init
          git config --local gc.auto 0
          git add --force .
          git commit -m "Automated deploy: $commit_message" >/dev/null

      - name: Push code to Pantheon MultiDev
        if: github.event.action != 'closed'
        run: |
          git remote add pantheon codeserver.dev.d2fe9d28-a99a-432f-963e-aaee6e0ecb15@codeserver.dev.d2fe9d28-a99a-432f-963e-aaee6e0ecb15.drush.in:2222/~/repository.git
          git push --force pantheon HEAD:$PANTHEON_SITE_ID.dev.$MULTIDEV_ENV

      - name: Delete Multidev Environment
        if: github.event.action == 'closed'
        run: |
          terminus env:delete $PANTHEON_SITE_ID.$MULTIDEV_ENV --yes --delete-branch