name: Pantheon Multidev Environments

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pantheon-multidev:
    runs-on: ubuntu-latest

    env:
      PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      MULTIDEV_ENV: pr-${{ github.event.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.2/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/

      - name: Install Terminus Build Tools
        run: |
          terminus self:plugin:install terminus-build-tools-plugin

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token="$PANTHEON_MACHINE_TOKEN"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"

      - name: Create or Update Multidev Environment
        if: github.event.action != 'closed'
        run: |
          ssh-add $SSH_KEY
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          terminus build:env:create $PANTHEON_SITE_ID.dev $MULTIDEV_ENV --yes
          terminus build:env:push $PANTHEON_SITE_ID.$MULTIDEV_ENV
          terminus drush $PANTHEON_SITE_ID.$MULTIDEV_ENV updb -y
          terminus drush $PANTHEON_SITE_ID.$MULTIDEV_ENV cim -y
          terminus drush $PANTHEON_SITE_ID.$MULTIDEV_ENV updb -y

      - name: Delete Multidev Environment
        if: github.event.action == 'closed'
        run: |
          terminus env:delete $PANTHEON_SITE_ID.$MULTIDEV_ENV --yes --delete-branch