name: Pantheon Multidev Environments

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pantheon-multidev:
    runs-on: ubuntu-latest

    env:
      PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
      PANTHEON_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      MULTIDEV_ENV: pr-${{ github.event.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.2/terminus.phar -o terminus
          chmod +x terminus
          sudo mv terminus /usr/local/bin/

      - name: Install Terminus Build Tools
        run: |
          terminus self:plugin:install terminus-build-tools-plugin

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token="$PANTHEON_MACHINE_TOKEN"

      - name: Create or Update Multidev Environment
        if: github.event.action != 'closed'
        run: |
          LAST_COMMITTER_NAME=`git log -1 --pretty=%cn`
          LAST_COMMITTER_EMAIL=`git log -1 --pretty=%ce`
          git config user.name "$LAST_COMMITTER_NAME"
          git config user.email "$LAST_COMMITTER_EMAIL"

      - name: Prepare code for deployment
        if: github.event.action != 'closed'
        run: |
          git log
          git remote
          git remote add pantheon ssh://codeserver.dev.$PANTHEON_SITE_ID@codeserver.dev.$PANTHEON_SITE_ID.drush.in:2222/~/repository.git
          git remote
          ssh-keyscan codeserver.dev.$PANTHEON_SITE_ID.drush.in
          git push pantheon HEAD:$MULTIDEV_ENV


      - name: Delete Multidev Environment
        if: github.event.action == 'closed'
        run: |
          terminus build:env:delete $PANTHEON_SITE_ID.$MULTIDEV_ENV --yes --delete-branch